name: Remote Build and Deploy on Laravel Update

on:
  push:
    branches:
      - master  # Triggers on pushes to the master branch.

jobs:
  laravel-update-and-deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment.

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # Checks out the repository code.

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Specifies the PHP version to use.
        extensions: mbstring, pdo_mysql  # Required extensions for Laravel.
        tools: composer:v2  # Use Composer v2

    - name: Connect to Remote Server and Run Update Commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        password: ${{ secrets.HOSTINGER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /var/www/html/hadathah.org/hadathah-app
          # Stash any local changes
          git stash
          # Pull the latest changes from the master branch
          git pull origin master
          # Ensure all dependencies are installed
          COMPOSER_ALLOW_SUPERUSER=1 composer install --no-interaction --prefer-dist
          # Run migrations with no interaction to bypass the production prompt
          # php artisan migrate:fresh --seed --force
          # Clear and cache configurations, routes, and views
          php artisan optimize:clear
          # Composer autoload optimization
          composer dump-autoload --no-interaction
